/**
 * Custom Nitro SSR renderer for TanStack Start.
 * TanStack Start 的自定义 Nitro SSR 渲染器。
 *
 * Nitro's default Vite renderer calls `fetch(req, { viteEnv: "ssr" })`.
 * In the packaged Node runtime this can fall through to native fetch and call
 * the same HTTP server again, causing recursive self-requests and 500 errors.
 * Nitro 默认 Vite renderer 会调用 `fetch(req, { viteEnv: "ssr" })`。
 * 在打包后的 Node runtime 中，这可能退回到原生 fetch 并再次请求同一个 HTTP server，
 * 造成递归自请求和 500 错误。
 *
 * This renderer directly imports the generated TanStack SSR service and invokes
 * its `fetch` handler, avoiding the `viteEnv` fetch bridge entirely.
 * 这里直接导入 TanStack 生成的 SSR service 并调用它的 `fetch` handler，
 * 从而绕过 `viteEnv` fetch bridge。
 */
export default async function ssrRenderer({ req }: { req: Request }) {
	// Generated by Nitro during `vite build`; no declaration file is emitted.
	// 该文件由 Nitro 在 `vite build` 期间生成，不会生成类型声明文件。
	// @ts-expect-error generated Nitro SSR service has no declaration file
	const server = await import("../../.nitro/vite/services/ssr/server.js");

	return server.default.fetch(req);
}
